### ISSUE TITLE
play all isn't finishing

### ISSUE THREAD

**Issue by rsharifnasab** [nainemom/saynum#1]
hello.
I am really interested in this project and watching it.

but the problem is that `play all one by one in order` isn't going to finish.
i have much stuff to do but i am stocked in playing in order mode.

BTW thanks for this awesome project.

**Comment by nainemom** [comment]
hi, thanks
I made this just for fun and I don't have enough time to develop it. but PR's are welcome.

**Comment by nainemom** [comment]
I just fix the mentioned issue btw.
