### ISSUE TITLE
Wrong output with five-digit numbers

### ISSUE THREAD

**Issue by arsalanses** [nainemom/saynum#2]
Hi,
For example numbers like: 20,000 or 30,000 and extra...
( pattern: f'{n},0000' for n in range(1, 10) )
We can hear 'o' after 20 means like:

'بیست و هزار' not 'بیست هزار'

I'd love to send you PR but I don't know JS unfortunately :(
I'm using python more often... but I don't know could I help with it or not :(

liebe grüße 🌱

**Comment by nainemom** [comment]
That's right. I'll try to fix it on my next free time. :smile:
